platform :ios, '11.0'
use_frameworks!

target 'App' do
  # Add your Pods here
  pod 'GCDWebServer', "~> 3.0"

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'TinyServer', :path => '/Users/Drew/Dev/Brutal Damage/ionic-game-clock/node_modules/TinyServer'
  # Do not delete
end
